//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerEF
{
    using DataAccessLayerCommon;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FinancialInstitutionEntities : DbContext
    {
        public FinancialInstitutionEntities()
            : base("name=FinancialInstitutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<ServicesDirectory> ServicesDirectories { get; set; }
        public virtual DbSet<ServicesHistory> ServicesHistories { get; set; }
    }
}
