////------------------------------------------------------------------------------
//// <auto-generated>
////     Этот код создан по шаблону.
////
////     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
////     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace DataAccessLayerEF
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class ServicesHistory
//    {
//        public int Id { get; set; }
//        public System.DateTime Date { get; set; }
//        public int EmployeeId { get; set; }
//        public int ServicesDirectoryId { get; set; }
//        public int ClientId { get; set; }
    
//        public virtual Client Client { get; set; }
//        public virtual Employee Employee { get; set; }
//        public virtual ServicesDirectory ServicesDirectory { get; set; }
//    }
//}
