////------------------------------------------------------------------------------
//// <auto-generated>
////     Этот код создан по шаблону.
////
////     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
////     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace DataAccessLayerEF
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class ServicesDirectory
//    {
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//        public ServicesDirectory()
//        {
//            this.ServicesHistories = new HashSet<ServicesHistory>();
//            this.Branches = new HashSet<Branch>();
//        }
    
//        public int Id { get; set; }
//        public string Name { get; set; }
    
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<ServicesHistory> ServicesHistories { get; set; }
//        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
//        public virtual ICollection<Branch> Branches { get; set; }
//    }
//}
